# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-05 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='images',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='images',
            name='likes',
            field=models.ManyToManyField(related_name='pics', to='gram.Profile'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
