# Generated by Django 3.2.9 on 2021-12-06 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gram', '0007_auto_20211206_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='images',
            name='liked',
            field=models.ManyToManyField(default=0, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='like', max_length=10),
        ),
    ]
