# Generated by Django 3.2.9 on 2021-12-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0008_auto_20211206_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='liked',
            new_name='like_count',
        ),
    ]
